SECTION -A 

Q.1 Ans-
create database company_db

Q.2 Ans-
create table empolyees(name varchar,id int,city varchar)
create table department(name varchar, id int,city varchar)

Q.3 Ans-
drop - permanetly delete the entire tables
truncate - removes all rows but retains the table structure
delete- removes specific rows based on condition

Q.4 Ans-
numeric- Integer, bigint,numeric,decimal
string-CHAR(n),VARCHAR(n),TEXT

Q.5 Ans-
varchar- varchar data type store variable format data
text-text does not require a specific maximum legth of character
char-char data type stores data of fixed length

-------------------------------------------------------------------------

SECTION B

Q.2 Ans-
update employee set salary =salary+ (salary*10/100);

Q.3 Ans-
delete from employees_table where hire_date<2022-01-01;

Q.4 Ans-
select * from employee_table where salary between 50000 and 80000;

Q.5 Ans-
select* from empolyees where  name like 'j%';

Q.6 Ans-
in postgre the returning clause is allows you to retrive data froms rows affected by insert, updatr,delete
statment without needing seprate select query.its particularly useful for accessing values generated by database
like auto incrementing ids or for returning specific columns after an operation

example-insert into customers (name,email)values ('john doe','johndoe@email.com')returning customer_id;

---------------------------------------------------------------------------------------------------------
Section C

Q.1 Ans-
select*from employees order by salary desc;

Q2.Ans-
select employess_name,salary from employees order by salary desc limit 3;

Q3.Ans-
select sum (salary) form empolyees table

Q4. Ans-
select avg (salary) from empolyees_table having avg(salary)<70000
------------------------------------------------------------------------------------------

SECTION D
Q.1 Ans-
select concat (first name ,' 'last name)from employees_table;

Q2.Ans-
select extract('year' from hir_date)from employees_table;

Q3.Ans-
select upper(first_name)from employees_table;

Q.4 Ans -
select extract('year'from age,(current_date ,hire_date ))from employees_table;

Q.5 Ans-
select date_trunc('month',hire_date)from employees_table;

-----------------------------------------------------------------------------------

SECTIN E
Q.1 Ans-
select coalesce(salary,50000)from empolyees table;

Q.2 Ans -
select gretest (salary) from employees_table;
select least(salary)from empoyees_table;

Q.3 Ans-
select (salary*100)/nullif ((select sum (salary))from emloyess_table,0)from empolyees_table;

---------------------------------------------------------------------------------------------------------------
SECTION F
Q.1 Ans-
select *from departments_table d inner join empoyees_table e on .dept_id =e.dept_id

Q2.Ans-
select *from departments table d left join empoyees_table e on d.dept_id=e.dept_id;

Q3.Ans
select dept_id from employees_table
except
select dept_id from department_table;

Q.4 Ans-
in sql
union combines the result of two or more select statements removing duplicate rows
union all combines them ,including all rows,even duplicates
example
select column 1,column 2 from table 1
union
select column 1,column 2 from table 2;
---------------------------------------------------------------------------------------------------------